create table if not exists public.artist_role_requests (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references public.profiles(id) on delete cascade,
    message text,
    status text not null default 'pending' check (status in ('pending','approved','rejected','cancelled')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    reviewed_at timestamptz,
    reviewed_by uuid references public.profiles(id) on delete set null,
    review_note text
);

create unique index if not exists artist_role_requests_one_pending_per_user
    on public.artist_role_requests(user_id)
    where status = 'pending';

create table if not exists public.admin_notifications (
    id bigint generated by default as identity primary key,
    kind text not null check (kind in ('artist_request', 'track_upload')),
    actor_user_id uuid references public.profiles(id) on delete set null,
    artist_request_id uuid references public.artist_role_requests(id) on delete cascade,
    track_id uuid references public.tracks(id) on delete cascade,
    created_at timestamptz not null default now(),
    read_at timestamptz,
    constraint admin_notifications_payload_check check (
        (kind = 'artist_request' and artist_request_id is not null and track_id is null)
        or (kind = 'track_upload' and track_id is not null and artist_request_id is null)
    )
);

alter table public.artist_role_requests enable row level security;
alter table public.admin_notifications enable row level security;

create policy artist_role_requests_select_own
on public.artist_role_requests for select
to authenticated
using (user_id = (select auth.uid()));

create policy artist_role_requests_select_admin
on public.artist_role_requests for select
to authenticated
using (public.current_user_is_admin());

create policy admin_notifications_select_admin
on public.admin_notifications for select
to authenticated
using (public.current_user_is_admin());

create policy admin_notifications_update_admin
on public.admin_notifications for update
to authenticated
using (public.current_user_is_admin())
with check (public.current_user_is_admin());

grant select on public.artist_role_requests to authenticated;
grant select, update on public.admin_notifications to authenticated;
revoke insert, update, delete on public.artist_role_requests from anon, authenticated;
revoke insert, delete on public.admin_notifications from anon, authenticated;

create or replace function public.current_user_is_artist()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select exists (
        select 1 from public.profiles as profile
        where profile.id = auth.uid()
          and profile.role in ('artist'::public.app_role, 'admin'::public.app_role)
    );
$$;

create or replace function public.enforce_artist_profile_invariant()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    if new.role in ('artist'::public.app_role, 'admin'::public.app_role) then
        perform public.provision_artist_for_profile(new.id);
    end if;
    return new;
end;
$$;

create or replace function public.submit_artist_role_request(request_message text default null)
returns public.artist_role_requests
language plpgsql
security definer
set search_path = ''
as $$
declare
    caller_id uuid := auth.uid();
    caller_role public.app_role;
    existing_request public.artist_role_requests;
    created_request public.artist_role_requests;
begin
    if caller_id is null then
        raise exception 'Authentication is required.' using errcode = '42501';
    end if;

    select role into caller_role from public.profiles where id = caller_id;
    if not found then
        raise exception 'Profile not found.' using errcode = 'P0002';
    end if;

    if caller_role <> 'listener'::public.app_role then
        raise exception 'Only listener accounts can request the artist role.' using errcode = '42501';
    end if;

    select * into existing_request
    from public.artist_role_requests
    where user_id = caller_id and status = 'pending'
    order by created_at desc
    limit 1;

    if found then return existing_request; end if;

    insert into public.artist_role_requests(user_id, message)
    values (caller_id, nullif(left(trim(coalesce(request_message, '')), 1000), ''))
    returning * into created_request;

    return created_request;
end;
$$;

create or replace function public.review_artist_role_request(
    target_request_id uuid,
    approve boolean,
    note text default null
)
returns public.artist_role_requests
language plpgsql
security definer
set search_path = ''
as $$
declare
    caller_id uuid := auth.uid();
    target_request public.artist_role_requests;
begin
    if caller_id is null or not public.current_user_is_admin() then
        raise exception 'Admin access is required.' using errcode = '42501';
    end if;

    select * into target_request
    from public.artist_role_requests
    where id = target_request_id
    for update;

    if not found then
        raise exception 'Artist request not found.' using errcode = 'P0002';
    end if;

    if target_request.status <> 'pending' then
        raise exception 'Artist request is already resolved.' using errcode = '55000';
    end if;

    if approve then
        update public.profiles set role = 'artist'::public.app_role where id = target_request.user_id;
    end if;

    update public.artist_role_requests
    set status = case when approve then 'approved' else 'rejected' end,
        reviewed_at = now(), reviewed_by = caller_id,
        review_note = nullif(left(trim(coalesce(note, '')), 1000), ''),
        updated_at = now()
    where id = target_request_id
    returning * into target_request;

    return target_request;
end;
$$;

revoke all on function public.submit_artist_role_request(text) from public, anon;
grant execute on function public.submit_artist_role_request(text) to authenticated;
revoke all on function public.review_artist_role_request(uuid, boolean, text) from public, anon;
grant execute on function public.review_artist_role_request(uuid, boolean, text) to authenticated;

create or replace function public.create_admin_notification_for_artist_request()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
    insert into public.admin_notifications(kind, actor_user_id, artist_request_id)
    values ('artist_request', new.user_id, new.id);
    return new;
end;
$$;

create or replace function public.create_admin_notification_for_track_upload()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
    if new.status = 'pending'::public.track_status then
        insert into public.admin_notifications(kind, actor_user_id, track_id)
        values ('track_upload', new.owner_id, new.id);
    end if;
    return new;
end;
$$;

create trigger artist_role_request_admin_notification
after insert on public.artist_role_requests
for each row execute function public.create_admin_notification_for_artist_request();

create trigger track_upload_admin_notification
after insert on public.tracks
for each row execute function public.create_admin_notification_for_track_upload();
